# Categories:

animals = ['ant', 'baboon', 'badger', 'bat', 'bear', 'beaver', 'camel', 'cat', 'clam', 'cobra', 'colossal squid', 'cougar', 'coyote', 'crow', 'deer', 'dog', 'donkey', 'duck', 'eagle', 'falcon', 'ferret', 'fox', 'frog', 'goat', 'goose', 'hawk', 'lion', 'lizard', 'llama', 'mole', 'monkey', 'moose', 'mouse', 'mule', 'newt', 'otter', 'owl', 'panda', 'parrot', 'peregrine falcon', 'pigeon', 'polar bear', 'python', 'rabbit', 'ram', 'rat', 'raven', 'rhino', 'salamander', 'salmon', 'scorpion', 'seal', 'shark', 'sheep', 'skunk', 'sloth', 'snake', 'spider', 'stork', 'swan', 'tiger', 'toad', 'trout', 'turkey', 'turtle', 'weasel', 'whale', 'wolf', 'wombat', 'zebra']

science = ['absolute zero', 'alpha decay', 'ampere', 'anion', 'antimatter', 'antiparticle', 'aristotle', 'astronomical unit', 'astronomy', 'astrophysics', 'atom', 'atomic structure', 'axiom', 'bandwidth', 'beaker', 'beta decay', 'biochemistry', 'biology', 'black hole',  'bohr-rutherford diagram', 'carbon', 'cation', 'cell membrane', 'celsius', 'centigrade', 'centripetal force', 'chemical', 'chemistry', 'chloroplast', 'chromosome', 'comet', 'cosmos', 'concentration', 'covalent compound', 'cytoplasm', 'dark energy', 'dark matter', 'dilution', 'dynamics', 'dyson sphere', 'ecliptic plane', 'energy', 'einstein', 'electricity', 'electrolysis', 'electrolyte', 'electromagnetism', 'electron', 'electron configuration', 'electronegativity', 'element', 'event horizon', 'evolution', 'experiment', 'fermi paradox', 'fibonacci', 'fission', 'foucault\'s pendulum', 'fusion', 'gamma decay', 'general relativity', 'genetics', 'genome', 'geode', 'geology', 'glucose', 'glycolysis', 'graduated cyllinder', 'gravitational singularity', 'gravity', 'half-life', 'heterogenous', 'homogeneous', 'homo sapien', 'hydrogen', 'hypothesis', 'infrared light', 'ionic compound', 'isotope', 'kardashev scale', 'kepler\'s laws', 'kinematics', 'laboratory', 'lepton', 'magnetism', 'magnitude', 'matrioshka brain', 'matter', 'meteorology', 'microbiology', 'microscope', 'microwave', 'mineral', 'mitochondrion', 'mixture', 'molarity', 'mole', 'molecule', 'neanderthal', 'neutrino', 'neutron', 'neutron star', 'newton', 'nikola tesla', 'observatory', 'orbital velocity', 'organism', 'orogeny', 'oxygen', 'paleontology', 'parsec', 'particle', 'periodic table', 'photon', 'photosynthesis', 'physics', 'polarity', 'proton', 'quantum mechanics', 'quark', 'radiation', 'reaction', 'recombinant dna', 'refraction', 'retrograde motion', 'ribosome', 'scalar', 'seismology', 'silicon', 'solar wind', 'solute', 'solution', 'solvent', 'spacetime', 'string theory', 'telescope', 'theory', 'thomas edison', 'time dilation', 'topoisomerase', 'transcription', 'ultraviolet light', 'vacuum', 'vacuum decay', 'valence', 'velocity', 'vertebrae', 'volcanology', 'wavelength', 'wormhole', 'zoology']

math = ['acute', 'additive principle', 'adjacent', 'algebra', 'algorithm', 'amplitude', 'angle', 'archimedes', 'asymptote', 'axis', 'bernoulli trial', 'binomial', 'calculus', 'cartesian plane', 'coefficient', 'continuity', 'cosecant', 'cosine', 'cotangent', 'covariance', 'decimal', 'denominator', 'derivative', 'difference', 'difference of squares', 'difference of cubes', 'differential', 'dimension', 'discontinuity', 'discrete', 'domain', 'end behaviour', 'equation', 'euclidian geometry', 'euler', 'exponent', 'exponentiation', 'expression', 'factorial', 'formula', 'fraction', 'function', 'geometry', 'googol', 'googolplex', 'hexagon', 'horizontal', 'hypotenuse', 'inequality', 'infinity', 'integer', 'integral', 'x-intercept', 'interior angle', 'intersection', 'inverse function', 'isosceles triangle', 'leibniz notation', 'line', 'linear', 'logarithm', 'matrix', 'monomial', 'multiplication', 'null set', 'numerator', 'oblique asymptote', 'obtuse', 'octagon', 'omega', 'origin', 'oval', 'parabola', 'parallel', 'parallelogram', 'pascal\'s triangle', 'pentagon', 'percent', 'percentile', 'perfect square', 'perimeter', 'periodic function', 'permutation', 'perpendicular', 'piecewise function', 'polygon', 'polynomial', 'power', 'principal angle', 'prism', 'probability', 'product', 'pyramid', 'pythagorean theorem', 'quadrant',  'quadratic formula', 'quadratics', 'quadrilateral', 'quotient', 'radian', 'range', 'ratio', 'rational function', 'reciprocal', 'remainder', 'rectangle', 'relative maximum', 'relative minimum', 'rhombus', 'right angle', 'root', 'rotation', 'scalar', 'secant', 'second derivative', 'semicircle', 'sequence', 'sigma', 'sine', 'sinusoid', 'slope', 'sphere', 'square', 'standard deviation', 'sum', 'symmetry', 'tangent', 'theorem', 'theta', 'transformation', 'translation', 'trapezoid', 'triangle', 'trigonometry', 'trinomial', 'union', 'variable', 'vector', 'velocity', 'vertex', 'vertical', 'vertice', 'volume', 'y-intercept', 'zero']

compSci = ['algorithm', 'application', 'array', 'artificial intelligence', 'binary', 'binary search', 'boolean', 'bootstrap', 'camel case', 'cascading style sheets', 'categorical data', 'concatenation', 'conditonal statement', 'database', 'data science', 'data structure', 'float', 'for loop', 'function', 'global variable', 'hypertext markup language', 'insertion sort', 'integer', 'iteration', 'java', 'javascript', 'linear search', 'list', 'local variable', 'logic gate', 'machine learning', 'module', 'nested loop', 'numerical data', 'ordinal data', 'parameters', 'program', 'python', 'recursion', 'responsive webpage', 'server', 'sigmoid function', 'software', 'string', 'structured data', 'structured query language', 'tuple', 'typescript', 'uml class diagram', 'while loop']

sports = ['badminton', 'baseball', 'basketball', 'boxing', 'cricket', 'curling', 'dodgeball', 'fencing', 'football', 'golf', 'ice hockey', 'javelin throw', 'karate', 'quidditch', 'rugby', 'skating', 'skiing', 'soccer', 'speed skating', 'swimming', 'table tennis', 'tennis', 'volleyball']

movies = ['annabelle', 'avatar', 'avengers', 'avengers: age of ultron', 'avengers: endgame', 'avengers: infinity war', 'beauty and the beast', 'captain america: civil war', 'captain america: the winter soldier', 'cars', 'cinderella', 'coraline', 'despicable me', 'doctor strange', 'malecifent', 'megamind', 'minions', 'godzilla', 'harry potter and the chamber of secrets', 'harry potter and the prisoner of azkaban', 'harry potter and the philosopher\'s stone', 'how to train your dragon', 'iron man', 'jurassic park', 'jurassic world', 'king kong', 'spider-man', 'spider-man: no way home', 'star wars: return of the jedi', 'star wars: revenge of the sith', 'star wars: the empire strikes back', 'terminator', 'the amazing spiderman', 'the godfather', 'the hobbit', 'the lion king', 'the little mermaid', 'the lorax', 'the pirates of the caribbean', 'thor: ragnarok', 'toy story', 'transformers', 'tron: legacy', 'venom', 'wall-e', 'wolverine']

movieCharacters = ['ahsoka tano', 'albus dumbledore', 'anakin skywalker', 'batman', 'black widow', 'boba fett', 'brian o\'conner',  'bumblebee', 'buzz lightyear', 'captain america', 'captain jack sparrow', 'captain marvel', 'carnage', 'chewbacca', 'count dooku', 'darth maul', 'darth sidious', 'darth vader', 'doctor octopus', 'dominic toretto', 'dormammu', 'electro', 'emperor palpatine', 'galactus', 'gandalf', 'general grievous', 'green goblin', 'grogu', 'groot', 'gru', 'han solo', 'harry potter', 'hawkeye', 'hermione granger', 'indiana jones', 'iron man', 'jabba the hutt', 'james bond', 'jango fett', 'joker', 'lord voldemort', 'luke skywalker', 'mephisto', 'nick fury', 'obi-wan kenobi', 'optimus prime', 'peter parker', 'princess leia', 'quicksilver', 'redskull', 'ron weasley', 'scarlet witch', 'severus snape', 'sirius black', 'star-lord', 'steve rogers', 'superman', 'thanos', 'the hulk', 'tom riddle', 'tony stark', 'tron', 'ultron', 'venom', 'vision', 'war machine', 'woody', 'yoda']

tvShows = ['attack on titan', 'cobra kai', 'deathnote', 'demon slayer', 'dragonball z', 'haikyuu', 'hunter x hunter', 'jujutsu kaisen', 'kuroko basketball', 'lego ninjago', 'modern family', 'money heist', 'naruto', 'parks and recreation', 'saiki k', 'squid game', 'the mandalorian', 'the office', 'wandavision', 'you']

customCategory = ['insert', 'your', 'own', 'words']

# If the user chooses a random category, the program selects a word from all the categories combined
randomCategory = animals + science + math + compSci + movies + movieCharacters + tvShows
